# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9b35d8b7-dd0e-4eb6-a80d-bd753728977f'
  imageRepository: 'contrastsecurityossspringpetclinic'
  containerRegistry: 'salesengineering.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'Microsoft Azure Sponsorship(4352f0e7-67db-4001-8352-25147175ee02)'
          KeyVaultName: 'demo-on-demand-vault'
          SecretsFilter: '*'
          RunAsPreJob: false
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'curl -X GET https://eval.contrastsecurity.com/Contrast/api/ng/$(contrast-id)/agents/default/JAVA -H ''''Authorization: $(contrast-auth)'''' -H ''''API-Key: $(contrast-key)'''' -H ''''Accept: application/json'''' -OJ'
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     command: buildAndPush
    #     repository: $(imageRepository)
    #     dockerfile: $(dockerfilePath)
    #     containerRegistry: $(dockerRegistryServiceConnection)
    #     tags: |
    #       $(tag)
