# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- 2.3.0_1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -al'
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship(4352f0e7-67db-4001-8352-25147175ee02)'
    KeyVaultName: 'demo-on-demand-vault'
    SecretsFilter: 'contrast-auth,contrast-key,contrast-org-id'
    RunAsPreJob: false
- task: Docker@2
  inputs:
    containerRegistry: 'SalesEngineering'
    repository: 'spring-petclinic'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '--build-arg CONTRAST__DOWNLOAD__SERVER="https://eval.contrastsecurity.com" --build-arg CONTRAST__DOWNLOAD__ORG_ID=$(contrast-org-id) --build-arg CONTRAST__DOWNLOAD__API_KEY=$(contrast-key) --build-arg CONTRAST__DOWNLOAD__AUTH=$(contrast-auth)'
- task: Docker@2
  inputs:
    containerRegistry: 'SalesEngineering'
    repository: 'spring-petclinic'
    command: 'push'
    tags: 'test'