# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  repositoryName: 'cs-demo-spring-petclinic'
  contrastServer: 'https://eval.contrastsecurity.com'
  appVersion: '2.3.0'
  demoVersion: '1'
  applicationName: 'Spring-Petclinic'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship(4352f0e7-67db-4001-8352-25147175ee02)'
    KeyVaultName: 'demo-on-demand-vault'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -X GET      https://eval.contrastsecurity.com/Contrast/api/ng/$(contrast-org-id)/agents/default/JAVA      -H "Authorization: $(contrast-auth)"   -H "API-Key: $(contrast-key)"      -H "Accept: application/json" > contrast.jar
- task: Docker@2
  inputs:
    containerRegistry: 'SalesEngineering'
    repository: $(repositoryName)
    tags: "$(appVersion)"
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '--build-arg CONTRAST__DOWNLOAD__SERVER="$(contrastServer)" --build-arg CONTRAST__DOWNLOAD__ORG_ID=$(contrast-org-id) --build-arg CONTRAST__DOWNLOAD__API_KEY=$(contrast-key) --build-arg CONTRAST__DOWNLOAD__AUTH=$(contrast-auth)'
- task: Docker@2
  inputs:
    containerRegistry: 'SalesEngineering'
    repository: '$(repositoryName)'
    command: 'push'
    tags: "$(appVersion)"
    addPipelineData: true
