name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest
    environment: CodeSec
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Build and Test
        run: ./mvnw --batch-mode verify

      - name: Contrast Scan Action
        uses: Contrast-Security-OSS/contrastscan-action@v2
        with:
          artifact: target/spring-petclinic-2.5.0-SNAPSHOT.jar
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
      #Upload the results to GitHub
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
